// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSMmyC7z3LZVuGfU2I8avOPOKJHHSHTs',
    appId: '1:701947184897:web:f4f3363d1747304d01bd00',
    messagingSenderId: '701947184897',
    projectId: 'redditfullstack-1aa9e',
    authDomain: 'redditfullstack-1aa9e.firebaseapp.com',
    storageBucket: 'redditfullstack-1aa9e.appspot.com',
    measurementId: 'G-5DVZ7NGKYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1iThF-SviMbpj2B6TZuPr6Oy0B8tpyac',
    appId: '1:701947184897:android:13a8c0fbf05c96f901bd00',
    messagingSenderId: '701947184897',
    projectId: 'redditfullstack-1aa9e',
    storageBucket: 'redditfullstack-1aa9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcAPjJ8lFp_3uBkzjc8SS9DgQUn9K2jFc',
    appId: '1:701947184897:ios:ab01722dba86458401bd00',
    messagingSenderId: '701947184897',
    projectId: 'redditfullstack-1aa9e',
    storageBucket: 'redditfullstack-1aa9e.appspot.com',
    iosBundleId: 'com.example.redditFullstack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwSMmyC7z3LZVuGfU2I8avOPOKJHHSHTs',
    appId: '1:701947184897:web:b9277459eac8d97801bd00',
    messagingSenderId: '701947184897',
    projectId: 'redditfullstack-1aa9e',
    authDomain: 'redditfullstack-1aa9e.firebaseapp.com',
    storageBucket: 'redditfullstack-1aa9e.appspot.com',
    measurementId: 'G-F0LMF3C57W',
  );
}
